### ISSUE TITLE
Variable length of non-POD element type  'Quaterniond'(aka "Quaternion<double>')

### ISSUE THREAD

**Issue by ios2010** [HKUST-Aerial-Robotics/VINS-Mobile#1]
macOS Sierra10.12 
Xcode 8.2.1 
iPhone 6plus
ios 10.0.1
issue #1
Variable length of non-POD element type  'Quaterniond'(aka "Quaternion<double>')
![40595ad9-4b73-4266-b73f-485f4e80fccb](https://cloud.githubusercontent.com/assets/10526800/25786347/fe2f9d84-33c5-11e7-821c-a437489228d5.png)
When building the project

**Comment by ios2010** [comment]
And we can solve the problem by changing the structure to a pointer.
![Uploading D8300BE7-2363-482D-BBF1-1A5A9ED101BC副本.jpg…]()

**Comment by github4dogg** [comment]
Good  job!

**Comment by tigerking** [comment]
Do not forget to release the memory before this function returned
>>>
if(q_array) delete[] q_array;
}
