### ISSUE TITLE
Status is fail...

### ISSUE THREAD

**Issue by KongCDY** [HKUST-Aerial-Robotics/VINS-Mobile#11]
I start the app, using iphone7 plus. The keypoints detection seems very stable, red points, sometimes are blue. But the status is fail_imu, fail_sfm, fail_align.......
How to play this app?

**Comment by PeiliangLi** [comment]
It's in the initialization process. Just give it some translations.

**Comment by qintony** [comment]
Without enough translation, the monocular visual-inertial system cannot optimize scale.

So the system will not work at absolutely stable status.

**Comment by KongCDY** [comment]
Thank you, I forget to change the project to release.
