### ISSUE TITLE
相机和imu外参标定

### ISSUE THREAD

**Issue by JumpXing** [HKUST-Aerial-Robotics/VINS-Mobile#114]
不好意思，我在学习VINS-Mobile的过程中遇到一个疑惑，不知道老师可不可以解答一下。
iphone手机上相机和imu之间的外参是如何获得的，就是那个tic、ric，两者之间的平移和旋转。在VINS-MONO中使用的是外部设备，可以直接测量，但是手机难道也是通过拆机测出的吗？

**Comment by IamMegatron2025** [comment]
@JumpXing 您好，我对这个tic、ric也很迷惑，能不能解释一下？

**Comment by JumpXing** [comment]
> @JumpXing 您好，我对这个tic、ric也很迷惑，能不能解释一下？

你可以说啊，交流一下
