### ISSUE TITLE
opencv_error exposure_compensate.hpp

### ISSUE THREAD

**Issue by EvanLiUAV** [HKUST-Aerial-Robotics/VINS-Mobile#12]
enum {NO, GAIN, GAIN_BLOCKS}
expected identifier

**Comment by EvanLiUAV** [comment]
![image](https://cloud.githubusercontent.com/assets/9546943/25900995/ed4e8b7a-35c7-11e7-8c74-51134e7d7273.png)

**Comment by EvanLiUAV** [comment]
Just solved.I modified enum{NO to enum{NO_other in blenders.hpp ,expose_compensate.hpp and replace NO with NO_other in blenders.cpp and expose_compensate.cpp. Then rebuild.

**Comment by sunkaianna** [comment]
If you use the specific opencv2.framework provided by authors and make sure you haven't installed the other versions in your mac, everything will be OK.
