### ISSUE TITLE
Signing problem

### ISSUE THREAD

**Issue by pmd2245** [HKUST-Aerial-Robotics/VINS-Mobile#125]
Hi,

I am novice with Xcode. This is probably a stupid question but I turn around a "signing" problem that I am not able to solve.
![capture d ecran 2018-11-29 a 08 53 44](https://user-images.githubusercontent.com/45447729/49207331-e6676a00-f3b4-11e8-99a0-ef6daeb800e3.png)

I would really appreciate if someone could help me!

Is there anyone who managed to test the app on iPhone X? 

Thanks in advance,
Pm

**Comment by btbufresh** [comment]
Hi, any progress on the issue above? I met the same problem as you, and still haven't solved it. Help needed...

**Comment by pmd2245** [comment]
Hi,

Unfortunately I did not find any solution. 
If you figure out something, please let me know.

Thanks,
Pierre-Marie

**Comment by pmd2245** [comment]
You must change the Bundle Identifier. I just deleted the dash and now it works well.
<img width="1678" alt="capture d ecran 2018-12-19 a 17 27 23" src="https://user-images.githubusercontent.com/45447729/50233341-86605400-03b3-11e9-948f-e36879779c48.png">
