### ISSUE TITLE
iphone7 FAIL_IMU

### ISSUE THREAD

**Issue by EvanLiUAV** [HKUST-Aerial-Robotics/VINS-Mobile#13]
STA: FAIL_IMU always shown on iphone7

**Comment by PeiliangLi** [comment]
So, have you solved the previous issue #12?
enum {NO, GAIN, GAIN_BLOCKS}
expected identifier

**Comment by EvanLiUAV** [comment]
Check your email

**Comment by EvanLiUAV** [comment]
I solved that problem by modified source code.

**Comment by PeiliangLi** [comment]
Please comment below #12 with how you solved it, thanks
