### ISSUE TITLE
Undefined symbol: google::log_sinks_global

### ISSUE THREAD

**Issue by JialingLiu-SLAM** [HKUST-Aerial-Robotics/VINS-Mobile#135]
I compiled the static library file of Ceres running on the simulator. However, when running on the simulator, the following errors were encountered
![屏幕快照 2020-05-30 下午8 49 18](https://user-images.githubusercontent.com/26592125/83328639-0d0ea580-a2b7-11ea-86b9-8405bb6a6650.png)
Can you give me some suggestions, or can you elaborate on how to generate the static library files of your Ceres ARM7. I don't know if I've missed anything.
In fact, I think there is a problem with the imported Google GLOG. I compiled a static library of GLOG, which still can't solve the problem.
Anyway, thank you very much

**Comment by wwdok** [comment]
how did you solve this problem, i met the same issue...
