### ISSUE TITLE
Weird Display on iPhone XS Max

### ISSUE THREAD

**Issue by BigJohnn** [HKUST-Aerial-Robotics/VINS-Mobile#148]
Hi, I have tested the code with my xs max, with small changes, 

https://github.com/BigJohnn/VINS-Mobile/tree/xsmax

everything is okay, except that the output image color is weird...
I have exported the input/output cv::Mat as .png files(which seem okay) for some single image processing, and have recorded the test video:

https://github.com/BigJohnn/VINS-Mobile/tree/xsmax/ScreenCapture

Any idea? Thx!

**Comment by GrooveWJH** [comment]
```
case iPhoneXSMax:
            printf("Device iPhoneXSMax plus param, 瞎写的。。\n");
            FOCUS_LENGTH_X = 526.600;
            FOCUS_LENGTH_Y = 526.678;
```


你这段都瞎写的，相机内参标定会影响一切。

**Comment by BigJohnn** [comment]
> ```
> case iPhoneXSMax:
>             printf("Device iPhoneXSMax plus param, 瞎写的。。\n");
>             FOCUS_LENGTH_X = 526.600;
>             FOCUS_LENGTH_Y = 526.678;
> ```
> 
> 你这段都瞎写的，相机内参标定会影响一切。

还没到那一步，  是说渲染效果比较奇怪
