### ISSUE TITLE
nothing changed when I run this app

### ISSUE THREAD

**Issue by latourst** [HKUST-Aerial-Robotics/VINS-Mobile#16]
![wechatimg35](https://cloud.githubusercontent.com/assets/14232249/25983264/3a175622-3716-11e7-8bc6-8cafeceb31e3.jpeg)
when i run this app on my iPhone7 nothing happened, no STA  and I have translated in the room,It seems nothing happened except some features .

**Comment by PeiliangLi** [comment]
Hi,
Firstly, you can pull our latest commit for better UI adaptation.
then make sure using the provided opencv, I guess you have got some logs like" wait for imu" or " throw Img"

**Comment by latourst** [comment]
下载下来的opencv是个文件夹不是opencv.framework...是直接拖到Xcode里面嘛？
