### ISSUE TITLE
Why limit device

### ISSUE THREAD

**Issue by gxl2024595** [HKUST-Aerial-Robotics/VINS-Mobile#17]
Hi
   I find that the lowest device become iphone6s. The earlier versions can run on iphone6 and ipad Air 2,and i want to konw why add the limit.

**Comment by PeiliangLi** [comment]
Hi,
It's for the performance guarantee. If you want to test the performance on iPhone6 or iPad Air, you can just relax the device limit on your repo.

**Comment by gxl2024595** [comment]
I run the Demo on iPad Air2 , it always crash here.please tell me why it did happen usually . And could you tell me  how to reslove the problem?

![e2828b73-3b89-40e6-be6c-f4acfa212b6a](https://cloud.githubusercontent.com/assets/16165921/25997699/d3a30852-374f-11e7-9ebf-b85a5997bd1e.png)

**Comment by PeiliangLi** [comment]
We didn't test it on iPad Air, so you need to tell me your modification in code.

**Comment by gxl2024595** [comment]
![66cde74d-9c1e-41ed-b65b-9b1073a97ead](https://cloud.githubusercontent.com/assets/16165921/25998652/a1678250-3754-11e7-9b78-224a236e8e7e.png)

i  relax the device limit, just modifi here.And the same error would present in earlier versions.

**Comment by qintony** [comment]
numerical stable issue. 
For example, long time stay still, IMU propagation, the covariance matrix become bigger and bigger.  So the information matrix bigger smaller and smaller. It will cause some numerically unstable issue.

We assert here to avoid this.

**Comment by gxl2024595** [comment]
Then how can I avoid this problem?

**Comment by zjupx** [comment]
I also met this assert in my iPhone6P. when I just use iphone 6sP 's params.  It seems all working fine at begining, but go to this assert later.

**Comment by gxl2024595** [comment]
@zjupx Hi,have you solved this problem?
