### ISSUE TITLE
VINS for LINUX ?

### ISSUE THREAD

**Issue by saimanoj18** [HKUST-Aerial-Robotics/VINS-Mobile#19]
Hello,

Firstly, congratulations on this amazing work. The accuracy seems amazing from the videos.

I am particularly looking for a VINS for a (camera and/or lidar) + IMU setup on Ubuntu. 

Can we use your work for my purpose ? I understand from a quick look that its only IOS devices. Could you provide any relevant references in that direction ?

Thanks

**Comment by qintony** [comment]
coming soon

**Comment by saimanoj18** [comment]
sounds great! Thanks

**Comment by TouqeerAhmad** [comment]
@qintony any updates on Ubuntu version of this without ROS
