### ISSUE TITLE
replicate results on Machine Hall datasets

### ISSUE THREAD

**Issue by K0stIa** [HKUST-Aerial-Robotics/VINS-Mobile#22]
Hi,

thanks a lot for sharing your implementation. I found it very educative.

I am trying to replicate your results from the paper, namely Figures 7-9 from the paper
"Monocular Visual-Inertial State Estimation for Mobile Augmented Reality".
Would it be possible to get the code for these tables as well?
I am currently trying to produce these results using your implementation, but constantly failing. :(

Thanks in advance,
Kostia.

**Comment by shaojie** [comment]
Thanks for your comments. We will release a ROS version next week. This should enable easy replication of all results on public datasets.

Best,
Shaojie
