### ISSUE TITLE
请问我将你们的代码拉到我的工程中，配置信息也相同

### ISSUE THREAD

**Issue by simpleant** [HKUST-Aerial-Robotics/VINS-Mobile#23]
为什么会报这个错：
#include "ceres/split.h" file not found
这个目录和文件都存在

**Comment by PeiliangLi** [comment]
build for your device instead of the simulator.

**Comment by simpleant** [comment]
我使用的是iphone 6s
目录下没有split.h头文件

**Comment by PeiliangLi** [comment]
please take a screenshot of your whole Xcode after compiling

**Comment by simpleant** [comment]
好的，谢谢
我给您发了邮件。里面包含Xcode工程截图
