### ISSUE TITLE
Unable to link to ceres-solver library

### ISSUE THREAD

**Issue by shubh-agrawal** [HKUST-Aerial-Robotics/VINS-Mobile#26]
Hi, I am having some problem while compiling your project in Xcode 8. The error messages convey to me that the project is unable to link to ceres-solver and also has "Undefined symbols for architecture x86_64". I am using MacOS Seirra and MacBook Pro

Here is a screenshot attached.
<img width="1272" alt="screen shot 2017-05-17 at 10 26 05" src="https://cloud.githubusercontent.com/assets/11351081/26147558/db8d8ffc-3aeb-11e7-94fe-79d072aaef94.png">
 
BTW, awesome work guys.

**Comment by PeiliangLi** [comment]
build for your device instead of simulator

**Comment by vilin777** [comment]
I am the same problem.I follow your setting, and project->build, still error. libceres.a is red.
![bdf430ce-2f70-460d-879e-341cf993b7f8](https://user-images.githubusercontent.com/10192800/27002221-9db6d1e4-4e0e-11e7-93c9-9ecd7169aa84.png)
