### ISSUE TITLE
imu-camera extrinsic calibration tools?

### ISSUE THREAD

**Issue by zjupx** [HKUST-Aerial-Robotics/VINS-Mobile#27]
Really thanks for this open code. 
1,  I want to know which calibration tools you used to calibrate the imu-camera extrinsic for the phone?
do you use kalibr tools for https://github.com/ethz-asl/kalibr/wiki/camera-imu-calibration?
if you use this tool,  I want to know these params for imu noise is right ?
----imu.yaml----
update_rate: 100.0 #Hz
accelerometer_noise_density: 0.5 #continous
accelerometer_random_walk: 0.002 
gyroscope_noise_density: 0.2 #continous
gyroscope_random_walk: 4.0e-5

2,  Another question for coordinate system. As read you code, I think the camera frame and imu/body frame is like this:

![coor](https://cloud.githubusercontent.com/assets/28749544/26192011/aee3a458-3be2-11e7-8899-6ebc5b96bfe8.jpg)

I am right for that ?

**Comment by PeiliangLi** [comment]
Hi, @zjupx 
It's not easy for calibrating the extrinsic param accurately using the open source calibration tool because of the temporal offsets between two sensors.
We find the sensor mount positions on the PCB and measure them by hand.

**Comment by zjupx** [comment]
thank you for you reply.

the other question has some print error. I upload pic instead:

![coor](https://cloud.githubusercontent.com/assets/28749544/26192091/f2cb1c3c-3be2-11e7-8aa2-628a2dc36a6d.jpg)

am I right for this coordinate system

**Comment by PeiliangLi** [comment]
Absolutely right.

**Comment by wchen61** [comment]
Hi, Peiliang. Accroding to zjupx's picture, the camera-imu rotation matrix will rotate 180 with x axis, which matrix will be:
1, 0, 0
0, -1, 0
0, 0, -1
But I know the camera-imu rotation matrix is:
0, -1, 0
1, 0, 0
0, 0, 1
Can you please tell me if I miss something?

**Comment by ShurlinLumens** [comment]
> Hi, Peiliang. Accroding to zjupx's picture, the camera-imu rotation matrix will rotate 180 with x axis, which matrix will be: 1, 0, 0 0, -1, 0 0, 0, -1 But I know the camera-imu rotation matrix is: 0, -1, 0 1, 0, 0 0, 0, 1 Can you please tell me if I miss something?

Did you figure out why is this happping? I run the datasets collected by iPad on PC, and I have to set 
R=[0,-1,0 ;
1,0,0;
0,0,1;]
in config.yaml, can VINS-Mono get a just passable trajectory.
Besides, the extrinsics parameter calibrated by Kalibr is more close to 
0,-1,0
1,0,0
0,0,1
not 
1, 0, 0
0, -1, 0
0, 0, -1

I am so anxious.～(　TロT)σ
