### ISSUE TITLE
你好，项目中的lateast_P和lateast_R分别表示什么

### ISSUE THREAD

**Issue by simpleant** [HKUST-Aerial-Robotics/VINS-Mobile#28]

**Comment by PeiliangLi** [comment]
it's the lateast position and rotation of your device corresponding to AR image.

**Comment by simpleant** [comment]
明白，谢谢🙏

**Comment by simpleant** [comment]
请问有没有安卓版本？

**Comment by PeiliangLi** [comment]
We don't have a plan to port to Android yet.
Thanks for attention.
