### ISSUE TITLE
程序一直提示"wait for imu, only should happen at the beginning"

### ISSUE THREAD

**Issue by victoryli88** [HKUST-Aerial-Robotics/VINS-Mobile#3]
iPhone 7

运行程序时，一直提示"wait for imu, only should happen at the beginning"，是需要配置么？

 if (!(imu_msg_buf.back()->header > img_msg_buf.front()->header))
        {
            NSLog(@"wait for imu, only should happen at the beginning");
            return measurements;
        }

**Comment by PeiliangLi** [comment]
hi,
Please make sure using the provides opencv2.framework instead of the official version.
If you cannot access dropbox, download it from https://pan.baidu.com/s/1b9O2Ai

**Comment by PeiliangLi** [comment]
use the opencv from https://pan.baidu.com/s/1o7F5FnW

**Comment by PeiliangLi** [comment]
hi,
Please make sure using the provides opencv2.framework instead of the official version.
If you cannot access dropbox, download it from https://pan.baidu.com/s/1o7F5FnW

**Comment by match08** [comment]
> hi,
> Please make sure using the provides opencv2.framework instead of the official version.
> If you cannot access dropbox, download it from https://pan.baidu.com/s/1o7F5FnW

Undefined symbols for architecture arm64:
  "cv::Mat::updateContinuityFlag()", referenced from:
      cv::Mat::Mat(int, int, int, void*, unsigned long) in VINS.o
