### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ouabout** [HKUST-Aerial-Robotics/VINS-Mobile#30]
Hi, thank you for releasing the code. I tried running it on my iphone 7 plus, I am seeing the tracked features, but it seems to be failing in initialization. The status is constantly switching between FAIL SFM, FAIL IMU and FAIL RELA. I tried switching between VINS and AR, toggling START/STOP, or hitting REINIT, nothing seems to help. Is there some specific way the system needs to be initialized?

**Comment by PeiliangLi** [comment]
Hi,
The most possible reason is that you build in debug mode.
