### ISSUE TITLE
程序运行后状态不收敛。

### ISSUE THREAD

**Issue by alongqiyue** [HKUST-Aerial-Robotics/VINS-Mobile#31]
你好。 我将程序中LOOP_CLOSURE设置为false，然后只跑VIO，initialization成功后状态不收敛，速度比较大(0.5m/s)，然后导致位置后面一直增加(即使是静止时)。加速度计和陀螺仪bias的估计比较正常(为10的负二次方量级)。不知道应该调哪些参数呢？

**Comment by PeiliangLi** [comment]
Hi, initialization is not directly related to loop-closure(if/not), please tell us:
1. how did you move the phone or just keep it static when the initialization diverge?
2. Did this occur only one time or every time in your device?

**Comment by alongqiyue** [comment]
你好，初始化时是将手机慢慢左右来回和上下来回移动，基本每次跑都会不收敛。

**Comment by PeiliangLi** [comment]
it's abnormal. Can you run it again without any modification of the origin code, then put some logs here？
