### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by pigqi** [HKUST-Aerial-Robotics/VINS-Mobile#32]
![snip20170525_2](https://cloud.githubusercontent.com/assets/27762984/26432173/6c90eb84-412c-11e7-8c8e-ecbff3f44b6f.png)
when I build ,have this error,
please help me , thank you

**Comment by PeiliangLi** [comment]
please find the solution in issue #1

**Comment by pigqi** [comment]
So quickly 
Thank you very much!
