### ISSUE TITLE
build error no member named 'findEssentialMat' in namespace 'cv'

### ISSUE THREAD

**Issue by tigerking** [HKUST-Aerial-Robotics/VINS-Mobile#34]
<img width="731" alt="2017-06-01 5 27 11" src="https://cloud.githubusercontent.com/assets/827176/26673466/97176f90-46ef-11e7-9dab-070574ebcd86.png">

**Comment by PeiliangLi** [comment]
please refer  #6

**Comment by tigerking** [comment]
I found another quick solution which does not required to uninstall opencv

The solution is to rename /usr/local/include/opencv2 to another folder name,eg Xopencv2.
So you need not uninstall opencv on your MAC. when you need opencv, rename the folder name from back to opencv2.
$sudo mv /usr/local/include/opencv2 /usr/local/include/Xopencv2

**Comment by PeiliangLi** [comment]
yes. of course right.
