### ISSUE TITLE
为什么把代码放到Unity3D工程里面，会变得很卡

### ISSUE THREAD

**Issue by MrLiOS** [HKUST-Aerial-Robotics/VINS-Mobile#36]
为什么把代码放到Unity3D工程里面，会变得很卡

**Comment by PeiliangLi** [comment]
We didn't test it in your unity project so we can't know why. Maybe it's because your unity seize cpu with vins.
And please **do not** open the exactly same issue. Thx

**Comment by MrLiOS** [comment]
thank for your answer. but i see some Unity3D code in  your project.You didn't meet in the use of this kind of situation?

**Comment by PeiliangLi** [comment]
I guess it depends on the cpu use rate of your unity project. 
In our project, unity activity affects the latency of vins slightly, but without loss performance.
You can use less feature number and solver time for vins, or optimize your unity code.
