### ISSUE TITLE
how to calc/set/adjust the params for new device ,eg iphone6p

### ISSUE THREAD

**Issue by tigerking** [HKUST-Aerial-Robotics/VINS-Mobile#37]
I do some modification to support iphone6p and it runs ok on iphone6p (IOS10.3.1).
When I test it and found that when I turn around and return the start point, it does not show the correct result. Is it because I am using wrong params for iphone6sp on iphone6p? If yes, how can I turning and get accurate params for iphone6p device. Thanks

Below are my modification
>>>>>
1. file: global_param.hpp
enum DeviceType
{
    iPhone7P,
    iPhone7,
    iPhone6sP,
    iPhone6s,
// +++++
    iPhone6,
    iPhone6P,
// +++++++ END
    iPadPro97,
    iPadPro129,
    unDefine
};

2. file: ViewController.mm
DeviceType deviceName()
{
...
// ++++ 
    else if(([device compare:@"iPhone7,1"] == NSOrderedSame))
    {
        printf("Device iPhone6p\n");
        device_type = iPhone6P;
    }
//+++ END
}

3. file:  global_param.cpp
bool setGlobalParam(DeviceType device)
{
//+++++ , params copied from  iphone6sp

      case iPhone6P:
            printf("Device iPhone6P param\n");
            FOCUS_LENGTH_X = 547.565;
            FOCUS_LENGTH_Y = 547.998;
            PX = 239.033;
            PY = 309.452;
            SOLVER_TIME = 0.08;
            FREQ = 3;
            //extrinsic param
            TIC_X = 0.0;
            TIC_Y = 0.065;
            TIC_Z = 0.0;
            return true;
            break;

// ++++ END

**Comment by PeiliangLi** [comment]
It's also because iPhone6 is not enough to solve it in real time.

**Comment by tigerking** [comment]
if these parameters are also one fact that affect the result ?. thx

**Comment by PeiliangLi** [comment]
Yes, right. You can tune these params for better performance.
