### ISSUE TITLE
opencv 的问题 

### ISSUE THREAD

**Issue by codefordead** [HKUST-Aerial-Robotics/VINS-Mobile#4]
build时候在这  enum {NO, GAIN, GAIN_BLOCKS }; 出现Expected identifier 错误

**Comment by PeiliangLi** [comment]
Hi, make sure your opencv2.framework is exactly like this
![wechatimg70](https://cloud.githubusercontent.com/assets/12999299/25796488/3ff05952-340c-11e7-9d2b-38d0fac6cf2f.jpeg)
