### ISSUE TITLE
Frame skip of AR display?

### ISSUE THREAD

**Issue by xiaodian2234** [HKUST-Aerial-Robotics/VINS-Mobile#42]
I find that you choose one frame every three frames, and only calculate accurate poses of these frames. So, if application only displays these frames, it looks like frame skipping. Can this project provide more frequency of pose by camera or IMU?  I saw this part in your paper 'Beside pose, we also have accurate veloc- ity and IMU bias estimation, which enable to propagate the camera pose with IMU data up to 100 Hz. This ensures low-latency AR experience'. I don't know what this part mean. Is that mean that this project can provide pose up to 100Hz by IMU that can be used by AR application? Thanks a lot.

**Comment by qintony** [comment]
We will release a 30Hz version soon.

As for,
 'Beside pose, we also have accurate veloc- ity and IMU bias estimation, which enable to propagate the camera pose with IMU data up to 100 Hz. This ensures low-latency AR experience'

you can see the VINS-Mono (https://github.com/HKUST-Aerial-Robotics/VINS-Mono)
The topic "vins_estimator/imu_propogate", who's frequency is equal with IMU.
