### ISSUE TITLE
a problem about scale initialization

### ISSUE THREAD

**Issue by vonzy** [HKUST-Aerial-Robotics/VINS-Mobile#44]
I read your paper and use your method for the initialization. I can get the right gyroscope bias, but can't get the correct scale, and it's very unstable. Here is the result for scale.(the correct scale is about 2)
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170611234759840-921264206.jpg)

I don't know what's wrong with it. The equation I used is as follow:
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170611234843872-428390528.png)

**Comment by qintony** [comment]
In this implementation code, we relax the initialization threshold for the better experience.

It's just an initial value to bootstrap the nonlinear system. We don't use it to calibrate the real scale all the time. 

In the paper, we use the strict threshold. Such as strict g limitation, IMU variance, and SfM cost.

**Comment by vonzy** [comment]
@qintony so if the threshold is relaxed, the scale could get wrong possibly (even negative? I wonder if my code get wrong?). could you tell me the strict threshold you used? thanks!!!

**Comment by vonzy** [comment]
@qintony moreover, the condition number of H is very huge, so the equation is easily influenced by any errors in b?

**Comment by qintony** [comment]
The equation is right. 
If alpha and beta don't contain much excitation (such as near stable, zero acceleration), the equation is fully unobservable, the H will be ill-conditioned, and any result will be solved.  Sometimes negatives happen.  The preconditions are that, alpha, beta and SfM structure should be as accurate as possible.  

Following are thresholds

accurate sfm
![screenshot from 2017-06-12 12 42 05](https://user-images.githubusercontent.com/11583558/27019622-bee39c94-4f6c-11e7-9bc9-fbc61fcdcc10.png)

good gravity
![screenshot from 2017-06-12 12 42 23](https://user-images.githubusercontent.com/11583558/27019624-c12694fc-4f6c-11e7-9a0c-235931226d79.png)

enough IMU excitation
![screenshot from 2017-06-12 12 43 02](https://user-images.githubusercontent.com/11583558/27019625-c322fe6c-4f6c-11e7-89bd-2a463414a9d3.png)


As for a general application, nobody wants to wait a long time to get a much accurate initial value. So we relax these thresholds, get a rough initial guess (much better than no initial guess).

**Comment by vonzy** [comment]
all right! thanks!
