### ISSUE TITLE
Build Framework failed

### ISSUE THREAD

**Issue by ChokWah** [HKUST-Aerial-Robotics/VINS-Mobile#45]
I want to  build  VINS-ios-framework Target  to  a framework for my project , build failed.
// step
Selected  VINS-ios-framework Target
add VINS_ios - info.plist to  VINS-ios-framework Target's info
Build Failed  : 
![jietu20170612-233146](https://user-images.githubusercontent.com/13447070/27041727-54927738-4fc7-11e7-9c93-2fa603efce22.jpg)

Maybe I did something wrong . Could you tell me about this ,Please?

**Comment by ChokWah** [comment]
Oh, My mistake.
I made some change in buildSetting like this . It works : Build Succeeded.

![jietu20170612-234056](https://user-images.githubusercontent.com/13447070/27042592-0d41ea28-4fca-11e7-9bd7-a5a0cf35fcae.jpg)

**Comment by Varvrar** [comment]
Hello ChokWah!
I manage to build VINS-ios-framework by adding missing .cpp files to Compile Sources. But I still can't understand how to use this framework in my app. It does not even have public headers.

Did you manage to use this framework in your project?

**Comment by yangxu-debug** [comment]
<img width="1365" alt="Image" src="https://github.com/user-attachments/assets/79eb0a3d-dea9-415e-af44-4d266b30fe96" /> can anyone help me in this problem when building project?
