### ISSUE TITLE
Where the thread '- (void)processImage:(cv::Mat&)image' is started?

### ISSUE THREAD

**Issue by RemyYang** [HKUST-Aerial-Robotics/VINS-Mobile#46]
I am reading the  file 'ViewController.mm', but cannot locate where the thread '- (void)processImage:(cv::Mat&)image' is started. Could anyboy please help me out of this dummy problem? Thank you very much!

**Comment by PeiliangLi** [comment]
Actually, processImage is called in the opencv library. Find it in https://github.com/PeiliangLi/opencv_modify/blob/master/cap_ios_video_camera.mm#L476

**Comment by RemyYang** [comment]
@PeiliangLi Thank you so much for your quik response! Now this issue can be closed.
