### ISSUE TITLE
How to export Camera+IMU data and VINS results?

### ISSUE THREAD

**Issue by enigmaqiao** [HKUST-Aerial-Robotics/VINS-Mobile#47]
Hello everyone, I'm trying to modify the code to get the camera images and IMU readings. There are codes to handle this need in the project, but they seem to be commented and some bit messy. What should I do to get the images and IMU data generated by the device?

**Comment by PeiliangLi** [comment]
Please note these 2 define:
//#define RECORD_VINS true
//#define READ_VINS true
Find the corresponding code block and you will find how to use it.
