### ISSUE TITLE
 'opencv2/hal/defs.h' file not found

### ISSUE THREAD

**Issue by wangyuezf** [HKUST-Aerial-Robotics/VINS-Mobile#5]
我用的opencv2.framework是你们百度网盘中提供的，但也会报错

**Comment by wangyuezf** [comment]
或者就报“opencv2/opencv.hpp”file not found

**Comment by PeiliangLi** [comment]
have your opencv2.framework been recognized by Xcode like 
![1](https://cloud.githubusercontent.com/assets/12999299/25794200/85ac5d6a-3402-11e7-9f5d-4a7c10a721b4.jpeg)

**Comment by wangyuezf** [comment]
能留下的联系方式或者微信／QQ号？方便我们快速的沟通问题，谢谢




------------------ 原始邮件 ------------------
发件人: "Peiliang";<notifications@github.com>;
发送时间: 2017年5月8日(星期一) 下午3:25
收件人: "HKUST-Aerial-Robotics/VINS-Mobile"<VINS-Mobile@noreply.github.com>; 
抄送: "Undo"<717228306@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [HKUST-Aerial-Robotics/VINS-Mobile] 'opencv2/hal/defs.h' file notfound (#5)




have your opencv2.framework been recognized by Xcode like

**Comment by PeiliangLi** [comment]
mystery1221

**Comment by PeiliangLi** [comment]
use the opencv from here  https://pan.baidu.com/s/1o7F5FnW
