### ISSUE TITLE
KeyFrameDatabase::optimize4DoFLoopPoseGraph error

### ISSUE THREAD

**Issue by kuonangzhe** [HKUST-Aerial-Robotics/VINS-Mobile#51]
Hi, 
In this function there showed me an error when Build and Run:
Quaterniond q_array[max_length];              
error: variable length array of non-POD element type 'Quaterniond'(aka 'Quaternion<double>')
What should I do to solve this? I followed the same instructions on github in Xcode. Thanks!

**Comment by PeiliangLi** [comment]
please refer #1

**Comment by kuonangzhe** [comment]
Thanks for the help!
