### ISSUE TITLE
very confused about jacobians

### ISSUE THREAD

**Issue by vonzy** [HKUST-Aerial-Robotics/VINS-Mobile#52]
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170617135406134-1700995615.png)
2. very very confused about imu factor part in the code!!  I read the paper of Forster 'IMU Preintegration on Manifold for Efficient Visual-Inertial Maximum-a-Posteriori Estimation', and find there are some difference about residual jocabians between you used and Forster  provided, can you provide the residual jocabians equations you used? 
3. Sorry for no developing experience with Eigen and Ceres yet, a very simple question maybe:  is function 'virtual bool Evaluate(double const *const *parameters, double *residuals, double **jacobians)' in ceres solver used to calculate residuals with the jacobians provided by developer? If so, I can't find where the code assign value to jacobians. I can only find the code assign value to matrixs like jacobian_pose_i,jacobian_pose_j and etc.

**Comment by vonzy** [comment]
Is anybody avaliable?

**Comment by vonzy** [comment]
@PeiliangLi

**Comment by PeiliangLi** [comment]
1.  NO. 
![image](https://user-images.githubusercontent.com/12999299/27389425-ed8047bc-56d0-11e7-844f-af5490626cb2.png)
2. Check our technical report https://github.com/HKUST-Aerial-Robotics/VINS-Mono/blob/master/support_files/paper/tro_technical_report.pdf and http://ieeexplore.ieee.org/document/7139939/ carefully, then you can find its derivation.
3. Yes. The jacobian is assigned here:
![image](https://user-images.githubusercontent.com/12999299/27389832-2b031758-56d2-11e7-8223-351019d24489.png)

**Comment by vonzy** [comment]
get it,thanks!
