### ISSUE TITLE
Another question about imu factor

### ISSUE THREAD

**Issue by vonzy** [HKUST-Aerial-Robotics/VINS-Mobile#55]
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170618202335931-2045117834.png)

**Comment by PeiliangLi** [comment]
1. q has only 3 DoF
2. It's not solved by close form. It was optimized by non-linear, we provide a good initial guess, and the cost function will converge in the minima.

**Comment by vonzy** [comment]
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170619124507226-880530010.png)
@PeiliangLi

**Comment by vonzy** [comment]
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170619124619460-1767880255.png)
@PeiliangLi

**Comment by PeiliangLi** [comment]
The system is observable if we fix the first pose.
Intuitively, when the second pose comes, it can be calculated by imu integration uniquely, then the features observed by 1rd & 2rd frame can be triangulated. 
Step by step.
If the camera moves in constant velocity when the imu data equals zero, the case you describe may happen.
