### ISSUE TITLE
not issue , just a confirmation 

### ISSUE THREAD

**Issue by amranov** [HKUST-Aerial-Robotics/VINS-Mobile#57]
Hi , thank you for this wonderful work 
i just run VINS-MONO successfully under ROS it works perfectly 
now im interesting on VINS-Mobile , i wanna know if ROS is necessary to run VINS-Moblile in android device or not 
regards

**Comment by PeiliangLi** [comment]
Hi,
VINS-Mobile only supports iOS platform currently and it doesn't depend on ROS.

**Comment by amranov** [comment]
got it , 
thank you 
regards ;
----- Original Message -----
