### ISSUE TITLE
no member named 'findEssentialMat' and 'recoverPos' in namespace cv

### ISSUE THREAD

**Issue by TonyMou** [HKUST-Aerial-Robotics/VINS-Mobile#6]
Hi, Li, thank you for your sharing, and I have a little problem while building the project.

build failed, and show Semantic issues ,like no member named 'findEssentialMat' and 'recoverPos' in namespace cv

**Comment by PeiliangLi** [comment]
Hi,
please make sure using the provided opencv2.framework.

**Comment by TonyMou** [comment]
Thanks for the reply and yes I am using the opencv u provide still not work

**Comment by hyhrob** [comment]
I'm facing the same issue. Have you resolved it? @TonyMou @PeiliangLi

**Comment by TonyMou** [comment]
You need to uninstall your OSX's opencv. @hyhrob

**Comment by hyhrob** [comment]
Yes, I have uninstalled it and the xcode can correctly find the header files  in opencv.framework in the thirdparty folder. But nothing changed.

**Comment by hyhrob** [comment]
sorry, my fault. I have used a wrong package about opencv2.framework.
I have changed some code and it now can running on iPhone6 plus. Maybe I used the initialization parameters of iPhone6s plus, it always lost its location.

**Comment by hyhrob** [comment]
Good job! @TonyMou

**Comment by tigerking** [comment]
Another solution is to rename /usr/local/include/opencv2 to another folder name,eg Xopencv2. 
So you need not uninstall opencv on your MAC. when you need opencv, rename the folder name from back to opencv2.
$sudo mv /usr/local/include/opencv2 /usr/local/include/Xopencv2
