### ISSUE TITLE
global_param.hpp C_PI = 3.1414926

### ISSUE THREAD

**Issue by kuonangzhe** [HKUST-Aerial-Robotics/VINS-Mobile#60]
Recently when I went throught the source code, I found that in file global_param.hpp, the C_PI is define as 3.1414926 in line 44:

#define C_PI 3.1414926  

What I knew the data should be 3.1415926535....

Will this affect the accuracy and capability of the system? What is the purpose of make this value smaller? 

Thank you so much!

**Comment by PeiliangLi** [comment]
It's my mistake, definitely.
Thank you pretty much for pointing out!

**Comment by kuonangzhe** [comment]
@PeiliangLi My pleasure~
