### ISSUE TITLE
midPointIntegration issues in integration_base.h 

### ISSUE THREAD

**Issue by kuonangzhe** [HKUST-Aerial-Robotics/VINS-Mobile#61]
Hi, 

I went throught the function **midPointIntegration** inside integration_base.h. Though I know that the paper used Euler for easy representation, and the code is using mid-point integration for better accuracy. But the Matrix F and V really has huge differences from paper. The closed issue explanning 15*18 structure of six channel is still not clear for me. 

I also went through the TRO_technical_report and the paper "Tightly-Coupled Monocular Visual-Inertial Fusion for Autonomous Flight of Rotorcraft MAVs", unfortunately, they cannot help with the implemental difference and understanding. 

Could you mind providing some inference or the structure of the mid-point Matrix result? Or some other material which is available from you or online that might help with understanding this? You know, the large difference between code and paper really made it suffering to study this:D

Thank you so much!

**Comment by kuonangzhe** [comment]
@PeiliangLi

**Comment by qintony** [comment]
Please check out 
https://github.com/HKUST-Aerial-Robotics/VINS-Mono/issues/14

**Comment by kuonangzhe** [comment]
@qintony Thanks for the help! Best regards!
