### ISSUE TITLE
Possible to implement on Linux ???

### ISSUE THREAD

**Issue by trinamntn08** [HKUST-Aerial-Robotics/VINS-Mobile#62]
i'm  really impressed by your method. So i'm working on project to evaluate different SLAM methods. 
I wonder if i can implement your approach on Linux with a data set available , for example: TUM, ... like others methods could.

**Comment by PeiliangLi** [comment]
Please check out to VINS-Mono: https://github.com/HKUST-Aerial-Robotics/VINS-Mono
