### ISSUE TITLE
Jacobian question again

### ISSUE THREAD

**Issue by vonzy** [HKUST-Aerial-Robotics/VINS-Mobile#63]
Hello, I have read paper _'Tightly-Coupled Monocular Visual-Inertial Fusion for Autonomous Flight of Rotorcraft MAVs'_ ,_'Technical Report VINS-Mono: A Robust and Versatile Monocular Visual-Inertial State Estimator'_ and _'IMU Preintegration on Manifold for Efﬁcient Visual-Inertial Maximum-a-Posteriori Estimation'_ carefully, and found there are some differences on jacobian calculation between the code and the papers. 
In paper _'Tightly-Coupled Monocular Visual-Inertial Fusion for Autonomous Flight of Rotorcraft MAVs'_ ,the jacobian for p,v,q part is 
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170629191525305-1861048431.png)
but in the code, it's 
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170629191614836-1373439767.png)
Also, in the paper 'IMU Preintegration on Manifold for Efﬁcient Visual-Inertial Maximum-a-Posteriori Estimation', the jacobians are
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170629191951461-516223951.png)
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170629192019008-1576262643.png)
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170629192043524-493105660.png)
There still some differences for bias part. I wonder what cause the difference.
And I also noticed that in the code the jacobian for attitude is defined for two situations:
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170629192604102-277343619.png)
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170629192620743-55413079.png)
![](http://images2015.cnblogs.com/blog/1158108/201706/1158108-20170629192639805-970115719.png)
I don't know what this is for, could you please explain it?

**Comment by vonzy** [comment]
@shaojie @qintony @PeiliangLi

**Comment by qintony** [comment]
The difference is caused by the different definition of variables and residual function. I suggest you derivate it by yourself then you can know the difference behind them.

**Comment by vonzy** [comment]
So why the jacobian of attitude is defined for two situation?

**Comment by qintony** [comment]
The comment version is used when bias estimation is off.
We keep it in debug purpose, to valid the IMU correction is right.
