### ISSUE TITLE
When i was running on iphone6s, it always shows initializing 0%

### ISSUE THREAD

**Issue by wm727955603** [HKUST-Aerial-Robotics/VINS-Mobile#67]
I am a novice developed by IOS. I downloaded opencv and boost, running on iphone6s successfully, but app has always shown "initialzing 0%", and the parameters on the right side of the screen have not changed, and what should I do to let the app run up as shown in the video.

**Comment by wm727955603** [comment]
![img_0877](https://user-images.githubusercontent.com/20918308/28258323-3ea7482a-6b03-11e7-92bc-a3c766b2e6ef.PNG)

**Comment by PeiliangLi** [comment]
1.  Please don't expect good result when your camera is facing the glass.
2. But initializing 0% is not the case above, you can refer #33

**Comment by wm727955603** [comment]
OK,thanks,I solved this problem.
