### ISSUE TITLE
newbee in ios

### ISSUE THREAD

**Issue by zdczdcc** [HKUST-Aerial-Robotics/VINS-Mobile#7]
I'm a newbee in ios.I used xcode to open your project cloned from the hub.It shows some error like in the below image.

![image](https://cloud.githubusercontent.com/assets/11731396/25812085/d1ab06c2-3447-11e7-9091-c91b9ebd1ea8.png)

**Comment by PeiliangLi** [comment]
Hi,
It does not mean an error, you can ignore them and just build VINS-ios.

**Comment by zdczdcc** [comment]
I just built it,and it reported some errors.
![image](https://cloud.githubusercontent.com/assets/11731396/25813333/bf750b0c-344b-11e7-8b00-93a0781ccba3.png)

**Comment by zdczdcc** [comment]
Like that it's an error from opencv.But the `opencv.framework` i used was downloaded from dropbox instead of the official version.

**Comment by PeiliangLi** [comment]
have you installed opencv in your Mac?

**Comment by TonyMou** [comment]
uninstall your OS's opencv and use the opencv.framework the author provided.

**Comment by zdczdcc** [comment]
@TonyMou @PeiliangLi you are all right.I uninstalled my mac's opencv and solved this problem.
