### ISSUE TITLE
Dependency Analysis error

### ISSUE THREAD

**Issue by shubh-agrawal** [HKUST-Aerial-Robotics/VINS-Mobile#71]
I have had already build the xcode before and made it run on iphone 6 before a month.
But now when I am trying to build the same, it gives me Dependency analysis error. I am a noob when it comes to Xcode projects. Here is the screen shot
![screen shot 2017-08-02 at 9 58 10 pm](https://user-images.githubusercontent.com/11351081/28884691-891d272e-77d0-11e7-820a-2ea7ab8441e5.png)

**Comment by sunkaianna** [comment]
Your projects need a code signing created by yourself. If you don't know how to do, you can google "xcode code signing.
