### ISSUE TITLE
How to get poses? 

### ISSUE THREAD

**Issue by vivekarvind** [HKUST-Aerial-Robotics/VINS-Mobile#73]
Hey,

I would like to get the SLAM poses out of the iOS app. As far I've glanced the code, I could find the variables "translation" and "rotation" in the solveRelativeRT() function in motion_estimator.cpp. Am I proceeding in the right direction? Please help. 

Thanks!

**Comment by PeiliangLi** [comment]
In ViewController.mm, latest_P, laetst_R is the latest position and rotation respectively.

**Comment by vivekarvind** [comment]
Thanks very much!
