### ISSUE TITLE
ceres problem？

### ISSUE THREAD

**Issue by danpeng2** [HKUST-Aerial-Robotics/VINS-Mobile#8]
Hi. .It shows some error like in the below image.

![_20170509094010](https://cloud.githubusercontent.com/assets/16464178/25832203/c6f7304e-349b-11e7-8a32-270d3ea705ad.png)
![_20170509094027](https://cloud.githubusercontent.com/assets/16464178/25832202/c6e8919c-349b-11e7-9a56-4587f4798b99.png)

**Comment by PeiliangLi** [comment]
Hi，
Have you chosen your device instead of simulator as the target when you built？

**Comment by danpeng2** [comment]
yes， I chose simulator as the target when I built

**Comment by danpeng2** [comment]
@PeiliangLi yes， I chose simulator as the target when I built

**Comment by PeiliangLi** [comment]
That's the problem. You should connect your device and choose your iPhone as the target.

**Comment by danpeng2** [comment]
@PeiliangLi thank you！  Compatible Devices have  iPhone6s but not  iPhone6？

**Comment by PeiliangLi** [comment]
yes. We have not tested it on iPhone6
