### ISSUE TITLE
ask help on understanding covariance and jacobian matrix calculation during imu preintegration

### ISSUE THREAD

**Issue by chaussitag** [HKUST-Aerial-Robotics/VINS-Mobile#81]
inside the body of function ["IntegrationBase::midPointIntegration(double _dt, ...)",](https://github.com/HKUST-Aerial-Robotics/VINS-Mobile/blob/master/VINS_ios/integration_base.h)  there's a long code block under the 'if(update_jacobian)' statement, which calculates a 15x15 matrix F:
<pre>
void midPointIntegration(double _dt, ... ...)
{
    ... ...
    if(update_jacobian)
    {
        ... ...
        MatrixXd F = MatrixXd::Zero(15, 15);
        F.block<3, 3>(0, 0) = Matrix3d::Identity();
        F.block<3, 3>(0, 3) = -0.25 * delta_q.toRotationMatrix() * R_a_0_x * _dt * _dt +
           -0.25 * result_delta_q.toRotationMatrix() * R_a_1_x * (Matrix3d::Identity() - R_w_x * _dt) * _dt * _dt;
        F.block<3, 3>(0, 6) = MatrixXd::Identity(3,3) * _dt;
        F.block<3, 3>(0, 9) = -0.25 * (delta_q.toRotationMatrix() + result_delta_q.toRotationMatrix()) * _dt * _dt;
        F.block<3, 3>(0, 12) = -0.25 * result_delta_q.toRotationMatrix() * R_a_1_x * _dt * _dt * -_dt;
        
        F.block<3, 3>(3, 3) = Matrix3d::Identity() - R_w_x * _dt;
        F.block<3, 3>(3, 12) = -1.0 * MatrixXd::Identity(3,3) * _dt;

        F.block<3, 3>(6, 3) = -0.5 * delta_q.toRotationMatrix() * R_a_0_x * _dt +
            -0.5 * result_delta_q.toRotationMatrix() * R_a_1_x * (Matrix3d::Identity() - R_w_x * _dt) * _dt;
        F.block<3, 3>(6, 6) = Matrix3d::Identity();
        F.block<3, 3>(6, 9) = -0.5 * (delta_q.toRotationMatrix() + result_delta_q.toRotationMatrix()) * _dt;
        F.block<3, 3>(6, 12) = -0.5 * result_delta_q.toRotationMatrix() * R_a_1_x * _dt * -_dt;

        F.block<3, 3>(9, 9) = Matrix3d::Identity();
        F.block<3, 3>(12, 12) = Matrix3d::Identity();
    }
    ... ...
}
</pre>

to my understanding, the matrix F is calculated according to formula (8) and (9) from [technical report](https://github.com/HKUST-Aerial-Robotics/VINS-Mono/blob/master/support_files/paper/tro_technical_report.pdf), and the variable **F** in the code is actually "I + Ft*delta_t" in formula (9). 
by reviewing the code carefully, i think that only following sub-blocks of matrix **F** is the same as what the formula (8) and (9) tells:
<pre>
F.block<3, 3>(0, 0) = Matrix3d::Identity();
F.block<3, 3>(0, 6) = MatrixXd::Identity(3,3) * _dt;

F.block<3, 3>(3, 3) = Matrix3d::Identity() - R_w_x * _dt;
F.block<3, 3>(3, 12) = -1.0 * MatrixXd::Identity(3,3) * _dt;

F.block<3, 3>(6, 6) = Matrix3d::Identity();
F.block<3, 3>(6, 9) = -0.5 * (delta_q.toRotationMatrix() + result_delta_q.toRotationMatrix()) * _dt;

F.block<3, 3>(9, 9) = Matrix3d::Identity();
F.block<3, 3>(12, 12) = Matrix3d::Identity();
</pre>

according the the formula (8) and (9) in [technical report](https://github.com/HKUST-Aerial-Robotics/VINS-Mono/blob/master/support_files/paper/tro_technical_report.pdf), i think some sub-blocks of matrix F, such as F.block<3, 3>(0, 3) and F.block<3, 3>(0, 9), should be zeros, but inside the code they get some non-zero value, 
did i misunderstand the formula and the code, or there's something missed in the paper?
would you please tell me where to find the formula for other non-zero blocks of matrix **F**, such as F.block<3, 3>(0, 3), F.block<3, 3>(0, 9), F.block<3, 3>(0, 12) etc. Detailed explanations are very welcome.

![17b0429e-2321-4cf3-a1c1-f7fb6761591f](https://user-images.githubusercontent.com/7485026/29461367-0490739a-845e-11e7-9263-f62d587c4d81.png)

**Comment by PeiliangLi** [comment]
Hi, please see #48 as reference
