### ISSUE TITLE
open cv  errors， can anybody help me？  Thanks

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [HKUST-Aerial-Robotics/VINS-Mobile#87]
open cv  errors， can anybody help me？  Thanks  
<img width="1073" alt="2017-09-11 5 03 40" src="https://user-images.githubusercontent.com/17830375/30266868-4e5f1dec-9713-11e7-9192-fdd0be648dd7.png">

**Comment by MyOnlyOnlySunshine** [comment]
My Mac used to installed the opencv2 , and it always appear those errors  like the pictures . I really  have no ideas  how to solve it . Thanks

**Comment by sunkaianna** [comment]
brew unlink opencv (or brew remove opencv)
or 
cd path-to-opencv2/build
sudo make uninstall

download opencv2.frameworks provided by authors

rebuild your project

and everything will be fine.

**Comment by MyOnlyOnlySunshine** [comment]
I have solved  that problem  ，really thaks
