### ISSUE TITLE
No reference for function cv::findEssentialMat and cv::recoverPose

### ISSUE THREAD

**Issue by lz199144** [HKUST-Aerial-Robotics/VINS-Mobile#9]
<img width="761" alt="wx20170509-173940 2x" src="https://cloud.githubusercontent.com/assets/3222205/25845357/339e1430-34e0-11e7-934a-75c8d6c6753f.png">

What's wrong?

**Comment by PeiliangLi** [comment]
you may installed opencv in your Mac, and the xcode link to it instead of the provided one.
You need to uninstall your OSX' opencv or hide it at least.
